Replace `#!/bin/bash` with `#!/usr/bin/env bash`
reactos/RosBE pull request #3
Opened 2018-05-29 13:40 UTC by DennisOSRM

This PR pulls the location of `bash` from the environment and makes any workarounds for systems like FreeBSD unnecessary that put the `bash` in a different directory.

2018-06-15 10:18 UTC, ColinFinck requested changes
Although I'm seeing /usr/bin/env used with "bash" for the first time, it seems to be a nice trick to get scripts running on multiple Unix operating systems. For example, FreeBSD has been officially supported by RosBE, but the README always advised users to create a symlink /bin/bash.
While /usr/bin/env is not strictly guaranteed either, it seems to work on more systems than /bin/bash (cf. https://www.howtogeek.com/276607)

However, improving this for real requires all .sh scripts that currently feature a #!/bin/bash line to be changed to #!/usr/bin/env bash, not just RosBE-Builder.sh.
Please do that before this PR can be merged.

Optionally, you may also remove the notice ("Please also make sure that the file "/bin/bash" exists. For example FreeBSD usually installs Bash into another directory, so you have to create a symbolic link "/bin/bash" to the executable file.") from both README files. But this can also be done in a later step. I won't consider this a blocker for merging this PR.

2018-06-19 13:22 UTC, DennisOSRM commented
Thanks for the feedback. Will amend the PR in the next couple of days.

2018-06-27 13:03 UTC, DennisOSRM commented
@ColinFinck 

> However, improving this for real requires all .sh scripts that currently feature a #!/bin/bash line to be changed to #!/usr/bin/env bash, not just RosBE-Builder.sh.
Please do that before this PR can be merged.

Did it for the files in `Base-i386` but left the Windows directory untouched for now. Didn't want to break the environment by accident as I have no setup to test it thoroughly.

> Optionally, you may also remove the notice ("Please also make sure that the file "/bin/bash" exists. For example FreeBSD usually installs Bash into another directory, so you have to create a symbolic link "/bin/bash" to the executable file.") from both README files. But this can also be done in a later step. I won't consider this a blocker for merging this PR.

Done, too.

Please let me know if there are additional changes necessary to get this merged.

2018-06-28 08:06 UTC, ColinFinck approved these changes

2018-06-28 08:06 UTC, merged

2018-06-28 08:07 UTC, ColinFinck commented
Merged! Thanks a lot for looking into this :)