[ROSBE][UNIX] Accept Yes/No answers with upper case letters
reactos/RosBE pull request #6
Opened 2018-12-26 19:10 UTC by Fraizeraust

As the commit message says, answering with upper case letters leads the script quitting. This patch should correct this behaviour.

2018-12-26 19:13 UTC, HeisSpiter requested changes
Can you uppercase instead of doing various comparisons?
(using bash syntax - if we accept being only bash 4 compliant, tr, awk, whatever method you prefer).

2018-12-26 20:04 UTC, Fraizeraust commented
@HeisSpiter I decided to use `tr` for uppercase conversion. Is it good now?

2018-12-26 21:57 UTC, HeisSpiter requested changes
Nota: test your changes before pushing the "push" button ;-).
`$ answer="yes"; echo "$answer" | tr '[a-z]' '[A-Z]'`
`YES`

2018-12-26 21:57 UTC, HeisSpiter commented on RosBE-Unix/Base-i386/RosBE-Builder.sh
>  					if [ "$answer" != "yes" ]; then
This won't work.

2018-12-26 21:57 UTC, HeisSpiter commented on RosBE-Unix/Base-i386/scripts/rosbelibrary.sh
>  		if [ "$answer" = "yes" ]; then
This won't work.

2018-12-26 21:57 UTC, HeisSpiter commented on RosBE-Unix/Base-i386/scripts/rosbelibrary.sh
> +		elif [ "$answer" = "no" ]; then
I'd rather let this change out.
It's not just about changing caps here.

2018-12-27 10:01 UTC, Fraizeraust commented
@HeisSpiter Would something like this be tolerable?
```Bash
if [[ "$answer" = [yY][eE][sS] ]]; then
```
I further tested the Bash script and the uppercase letters are accepted in the input as you can see below (yes and YES also do work). I dropped the `tr` method because it always gave me `command not found` and syntax errors (this is the first time I touch Bash script).

```
Do you really want to continue? (yes/no)
[no] Yes

Checking for the needed tools...
Checking for as... OK
Checking for bison... OK
Checking for flex... OK
Checking for gcc... OK
Checking for g++... OK
Checking for grep... OK
Checking for makeinfo... OK
Checking for python... OK
Checking for GNU Make... OK
Checking for pkg-config... OK
Checking for zlib... OK

Installation Directory
In which directory do you want to install it?
Enter the path to the directory here or simply press ENTER to install it into the default directory.
[/usr/local/RosBE] 
```

2019-03-16 10:24 UTC, learn-more commented
@HeisSpiter How about these changes?

2019-12-25 07:11 UTC, merged